### ISSUE TITLE
Email Subscribe Prompt on Each Launch

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework#130]
Hi,

one of my customers keeps getting the email subscribe prompt with each launch, while it is configured to only show up after 5 days:

`PaddleToolKit.sharedInstance().presentEmailSubscribePrompt(withSchedule: "5 days", message: nil)`

I am using the latest framework (3.0.19).

Is there any further information I can provide? If you need to get in touch with the end user, please let me know at support@charliemonroe.net.

Thanks!

**Comment by GregularExpressions** [comment]
Hey @charlieMonroe,

We've seen some issues lately around Apple's new(ish) App Translocation functionality in MacOS Sierra, do you know if the user is running Sierra and if they're launching the app from within their Applications directory or somewhere else (Downloads maybe?)

Thanks,
Greg.

**Comment by charlieMonroe** [comment]
Hi,

no - it was reported to me before High Sierra was available.

Thanks!

**Comment by GregularExpressions** [comment]
Hey Charlie,

App Translocation was introduced in 10.12 (Sierra), it it feasible the user was on that version?

Thanks,
Greg.

**Comment by charlieMonroe** [comment]
Sorry, I misread your response - I thought your were asking about High Sierra. It is most likely that it was on macOS 10.12.

**Comment by GregularExpressions** [comment]
That's no problem, is the problem ongoing for the user? We believe moving the app inside the Applications directory should resolve it.

It's to do with app code signing as a whole and Apple taking the security measure of providing temporary files and directories away from the main system then not allowing the next launch access to them. We're looking at how we can help prevent this happening in future.

**Comment by charlieMonroe** [comment]
Hi,

yes, the customer reports that it is still happening. The app is in the Applications directory.

**Comment by GregularExpressions** [comment]
Hey Charlie,

Can you arrange to get a copy of the following file please:

~/Library/Application Support/App Name/paddata.padl

It should help us further debug, you can email it to me on greg@paddle.com.

Thanks,
Greg.

**Comment by charlieMonroe** [comment]
Hi Greg,

I've asked the customer to send you the data. In case it matters, the app is sandboxed, so the license data is in 

`~/Library/Containers/com.fuelcollective.eon/Data/Library/Application Support/Eon/`

**Comment by GregularExpressions** [comment]
Thanks Charlie, we have the file and I've forwarded it onto the SDK team to look at.
