### ISSUE TITLE
Random crashes on startup

### ISSUE THREAD

**Issue by paweldudek** [PaddleHQ/Mac-Framework#193]
So I'm having issues with Paddle SDK randomly crashing on application startup with following symbols in Paddle:

```
Application Specific Information:
objc_msgSend() selector name: respondsToSelector:


Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff557d0e9d objc_msgSend + 29
1   com.paddle.Paddle             	0x00000001035e215a -[PADProduct productConnectionFinished:] + 6234
2   com.paddle.Paddle             	0x00000001035e01ca __42-[PADProduct productInfo:apiKey:vendorId:]_block_invoke_2 + 42
3   libdispatch.dylib             	0x00007fff5639c591 _dispatch_call_block_and_release + 12
4   libdispatch.dylib             	0x00007fff56394d50 _dispatch_client_callout + 8
5   libdispatch.dylib             	0x00007fff563a032d _dispatch_main_queue_callback_4CF + 1148
6   com.apple.CoreFoundation      	0x00007fff2eaf5929 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
7   com.apple.CoreFoundation      	0x00007fff2eab7bea __CFRunLoopRun + 2586
8   com.apple.CoreFoundation      	0x00007fff2eab6f43 CFRunLoopRunSpecific + 483
```

This is becoming somewhat of a problem for us as it happens e.g. after users update the app via Sparkle. It crashes then on relaunch for 2-3 times and starts working afterwards. 

Is there something I'm doing wrong with the SDK? Any specific thread I should be calling it from? Should I wait till application finishes launching and only do it then?

**Comment by GregularExpressions** [comment]
Hey @paweldudek 

Thanks for the report, we've not received widespread report of this so we believe it's limited to a specific set of SDK calls on App Launch.

Can you let me know / paste a code sample of the SDK calls you make on app launch please and we'll investigate.

Thanks,
Greg.

**Comment by paweldudek** [comment]
@GregularExpressions thanks for the reply. 

Sure, here's a quick gist of what we're doing. Basically from `applicationWillFinishLaunching` we call the following:

```
        paddle.setApiKey(paddleAPIKey)
        paddle.setProductId(productID)
        paddle.setVendorId(vendorID)

        paddle.canForceExit = true

        paddle.startLicensingSilently(productInfo(), timeTrial: true)
        paddle.setCustomCheckoutAttributes([
            kPADCheckoutAllowQuantity: "0",
        ])
```

In `applicationDidFinishLaunching` we call the following:

```
        if paddle.activatedLicenceCode() != nil {
            paddle.verifyLicence { b, error in
                // here we handle the case, but no Paddle related calls
            }
        }
```

And after some time passes and we finish setting up all our application UI we call the following:

```
paddle.startLicensing(productInfo(), timeTrial: true, with: window)
```

The `productInfo()` function contains following info:

```
func productInfo() -> [String: String] {
    return [
        kPADProductName: "XYZ",
        kPADCurrentPrice: "29.99",
        kPADDevName: "XYZ",
        kPADCurrency: "EUR",
        kPADTrialDuration: "7",
        kPADImage: "http://www.example.com/image.png",
        kPADTrialText: "Thanks for downloading a trial of our product",
        kPADProductImage: "paddleicon.png", //Image file in your project,
    ]
}
```

Now that I pasted this I noticed `paddleicon.png` is missing from our project. I'm not sure if this could be the cause.

**Comment by GregularExpressions** [comment]
Hey @paweldudek 

Thanks for the breakdown, we've isolated the issue and it's a bug in the SDK. From your perspective, how urgently do you need a fix? Do you have an idea of what sort of percentage of launches are crashing like this?

Thanks,
Greg.

**Comment by paweldudek** [comment]
So we actually pulled an update with important bug fixes as we got reports users started seeing the crash after updating the app and launching it again. 

Plus we have some users reporting that this crash occurs on first launch after they download the app and open it, so it's not a pleasant experience and definitely puts our product in a bad light. 

Hence I'd say pretty urgent at this point 😊

**Comment by GregularExpressions** [comment]
Hey @paweldudek 

Thanks for the additional context, we'll look into getting this resolved ASAP - I'm hopeful it can be in the next few days.

Thanks,
Greg.

**Comment by GregularExpressions** [comment]
Hey @paweldudek 

We believe we've fixed this for the next release, we're just wrapping up the other items for this release and we'll ship it.

Thanks,
Greg.

**Comment by GregularExpressions** [comment]
Hey @paweldudek 

We've shipped the fix for this now in [v3.0.33](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.33). Let me know if you continue to see this issue.

Thanks,
Greg.

**Comment by paweldudek** [comment]
@GregularExpressions unfortunately I'm still seeing this, some users report the app entering a crash loop after updating. 

We've released an update about 12 h yesterday and I already have 5 people not being able to run the app because it enter a crash loop every time it's opened. In our crash reporting tool I see the same symbols in Paddle SDK as before. 

It's a bit embarrassing for our users as the most resilient guy tried to open the app 5 times in a row and it crashed every time. 

What can I do to help you fix this?

**Comment by GregularExpressions** [comment]
Hey @paweldudek 

Sorry to hear there are still some issues.

We're struggling to replicate, could you arrange for me to get a copy of the build that exhibits the issue please - and any additional details that might help, i.e macOS versions, new or upgrading users, etc.

I'm greg at paddle dot com if you'd prefer to email.

Thanks,
Greg.

**Comment by paweldudek** [comment]
Hey @GregularExpressions I sent you an email a couple of days ago - did I hit a spam filter? :(

**Comment by GregularExpressions** [comment]
Hey @paweldudek 

No panic, I received the email and we've been investigating - some work around GDPR has meant it's moved a little slower than normal.

 I'll see if I can get you an update today.

Thanks,
Greg.

**Comment by paweldudek** [comment]
That's great! I'd love to at least have a workaround, I'm seeing more and more users affected by this in our crash reporting tools.

**Comment by GregularExpressions** [comment]
Fixed in [v3.0.33](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.33)

**Comment by GregularExpressions** [comment]
@paweldudek did you have any luck retesting with the debug build we sent you please?

**Comment by paweldudek** [comment]
@GregularExpressions so we released our app with the updated SDK and it looks like the issue is gone! 👍 Thank you!
